name: ASP.NET Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build and Publish project
        run: dotnet publish --configuration Release --output ./publish
        
      - name: Copy to Windows Server
        uses: garygrossgarten/github-action-ssh@release
        with:
          host: ${{ secrets.WINDOWS_SERVER_HOST }}
          username: ${{ secrets.WINDOWS_SERVER_USERNAME }}
          password: ${{ secrets.WINDOWS_SERVER_PASSWORD }}
          port: ${{ secrets.WINDOWS_SERVER_PORT }}
          command: powershell -Command "Copy-Item -Recurse -Force ./publish/* C:\inetpub\chat.jafartest.com"
